simple:
	gcc -Wall main.c -o main -lm
	# adding -lm to make math.h library work

clean:
	rm -f *.o main
	rm -f pomiar_zad_4.txt a.txt

test:
	make clean
	make simple
	./main dane.txt a.txt systemy operacyjne
